# Generated by Django 4.2.1 on 2023-05-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseDate', models.DateField(auto_now=True)),
                ('PurchaseQuantity', models.IntegerField()),
                ('PurchasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('GoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.good')),
            ],
        ),
    ]
