# Generated by Django 4.2.1 on 2023-05-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodName', models.CharField(max_length=50)),
                ('GoodDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('GoodCategory', models.CharField(max_length=50)),
                ('GoodQuantity', models.IntegerField()),
                ('GoodBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('GoodPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StorageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage')),
            ],
        ),
    ]
